# Generated by Django 3.2.13 on 2022-09-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice0929App', '0002_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=3),
        ),
    ]
